version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # Jaeger agent
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=9411
