name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore taxrecon.sln
      - name: Build
        run: dotnet build taxrecon.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test taxrecon.sln --no-build --configuration Release --logger trx
